version: 2
jobs:
  release:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - setup_remote_docker
      - run: ./scripts/release.sh

workflows:
  version: 2
  build:
    jobs:
      - release:
          context: Github
          filters:
            tags:
              only: /.*/
